import fetch from 'node-fetch';

/**
 * Interface for the payload structure sent to the session logger backend.
 * 傳送到 session logger 後端之酬載結構的介面。
 */
export interface LogPayload {
    sessionId: string; // Unique identifier for the current session. 目前會話的唯一識別符。
    prompt: string;    // The prompt text provided by the user. 使用者提供的提示文本。
    response: string;  // The response generated by the AI. AI 生成的回應。
    responseTimeMs?: number; // Optional: Time taken to generate the response in milliseconds. 選填：生成回應所需時間（毫秒）。
    provider?: string; // Optional: The AI provider used (e.g., 'OpenAI', 'Anthropic'). 選填：使用的 AI 提供者（例如 'OpenAI'、'Anthropic'）。
    model?: string;    // Optional: The specific AI model used (e.g., 'gpt-4', 'claude-3'). 選填：使用的特定 AI 模型（例如 'gpt-4'、'claude-3'）。
    type?: 'resolve' | 'edit' | 'chat'; // Optional: Type of interaction (e.g., 'resolve' for code resolution, 'edit' for code modification, 'chat' for general chat). 選填：互動類型（例如 'resolve' 用於程式碼解析，'edit' 用於程式碼修改，'chat' 用於一般聊天）。
}

/**
 * SessionLogger class handles sending log data to a backend analytics service.
 * It's designed to be fire-and-forget, ensuring it doesn't block the main application flow.
 * SessionLogger 類別負責將日誌資料發送到後端分析服務。
 * 它被設計為「即發即忘」，以確保不會阻塞主應用程式流程。
 */
export class SessionLogger {
    private backendUrl: string; // The URL of the analytics backend. 分析後端的 URL。

    constructor() {
        // Initializes the backend URL. It uses the ANALYTICS_BACKEND_URL environment variable
        // if available, otherwise defaults to 'http://localhost:3000'.
        // 初始化後端 URL。如果 ANALYTICS_BACKEND_URL 環境變數存在，則使用該變數，
        // 否則預設為 'http://localhost:3000'。
        this.backendUrl = process.env.ANALYTICS_BACKEND_URL || 'http://localhost:3000';
    }

    /**
     * Sends a log payload to the backend. This operation is fire-and-forget,
     * meaning it does not wait for a response and silently handles errors
     * to prevent blocking the main thread or disrupting the CLI experience.
     * It also includes a short timeout for the network request.
     *
     * 將日誌酬載發送到後端。此操作為「即發即忘」，
     * 意味著它不等待回應並靜默處理錯誤，
     * 以防止阻塞主執行緒或中斷 CLI 體驗。
     * 它還包含網路請求的短暫逾時。
     *
     * @param payload The log data to send. 要發送的日誌資料。
     * @returns A Promise that resolves once the logging attempt is made,
     *          regardless of success or failure.
     *          一個 Promise，無論成功或失敗，一旦日誌嘗試完成即解析。
     */
    async log(payload: LogPayload): Promise<void> {
        // If no backend URL is configured or analytics are disabled via environment variable,
        // stop execution immediately.
        // 如果沒有配置後端 URL，或者透過環境變數禁用了分析功能，
        // 則立即停止執行。
        if (!this.backendUrl || process.env.DISABLE_ANALYTICS === 'true') {
            return;
        }

        try {
            // Use AbortController for setting a timeout for the fetch request.
            // 使用 AbortController 為 fetch 請求設置逾時。
            const controller = new AbortController();
            // Set a 3-second timeout for the request.
            // 為請求設置 3 秒逾時。
            const timeoutId = setTimeout(() => controller.abort(), 3000);

            try {
                // Send a POST request to the backend with the log payload and a timestamp.
                // 發送一個 POST 請求到後端，包含日誌酬載和時間戳。
                await fetch(`${this.backendUrl}/events`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        ...payload,
                        timestamp: new Date().toISOString(), // Add current timestamp to the payload. 將當前時間戳添加到酬載。
                    }),
                    // Associate the AbortController signal with the fetch request for timeout handling.
                    // 將 AbortController 信號與 fetch 請求關聯，用於處理逾時。
                    signal: controller.signal as any,
                });
            } finally {
                // Ensure the timeout is cleared regardless of the fetch outcome.
                // 無論 fetch 結果如何，都確保清除逾時。
                clearTimeout(timeoutId);
            }
        } catch (error) {
            // Silently fail: Do nothing if the analytics backend is unreachable or any other error occurs.
            // This guarantees we don't break the CLI experience for the user.
            // 靜默失敗：如果分析後端無法訪問或發生任何其他錯誤，則不執行任何操作。
            // 這保證我們不會破壞使用者的 CLI 體驗。
            if (process.env.DEBUG === 'true') {
                // If DEBUG environment variable is true, log the error to the console.
                // 如果 DEBUG 環境變數為 true，則將錯誤記錄到控制台。
                console.debug('[SessionLogger] Failed to send log to backend:', error);
            }
        }
    }
}
