import fetch from 'node-fetch';

/**
 * Interface for the payload structure sent to the session logger backend.
 */
export interface LogPayload {
    sessionId: string;       // Unique identifier for the current session.
    prompt: string;          // The prompt text provided by the user.
    response: string;        // The response generated by the AI.
    responseTimeMs?: number; // Optional: Time taken to generate the response in milliseconds.
    provider?: string;       // Optional: The AI provider used (e.g., 'OpenAI', 'Anthropic').
    model?: string;          // Optional: The specific AI model used (e.g., 'gpt-4', 'claude-3').
    type?: 'resolve' | 'edit' | 'chat'; // Optional: Type of interaction.
}

/**
 * SessionLogger sends log data to a backend analytics service.
 * Designed to be fire-and-forget so it never blocks the main application flow.
 */
export class SessionLogger {
    private backendUrl: string;

    constructor() {
        // Use ANALYTICS_BACKEND_URL if set, otherwise fall back to localhost.
        this.backendUrl = process.env.ANALYTICS_BACKEND_URL || 'http://localhost:3000';
    }

    /**
     * Send a log payload to the backend. Fire-and-forget: does not await a
     * response and silently swallows errors to avoid disrupting the CLI.
     * Includes a 3-second timeout on the network request.
     *
     * @param payload The log data to send.
     */
    async log(payload: LogPayload): Promise<void> {
        // Skip if analytics are disabled or no backend URL is configured.
        if (!this.backendUrl || process.env.DISABLE_ANALYTICS === 'true') {
            return;
        }

        try {
            const controller = new AbortController();
            const timeoutId = setTimeout(() => controller.abort(), 3000);

            try {
                await fetch(`${this.backendUrl}/events`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        ...payload,
                        timestamp: new Date().toISOString(),
                    }),
                    signal: controller.signal as any,
                });
            } finally {
                clearTimeout(timeoutId);
            }
        } catch (error) {
            // Silently fail — do not break the CLI experience.
            if (process.env.DEBUG === 'true') {
                console.debug('[SessionLogger] Failed to send log to backend:', error);
            }
        }
    }
}
